server:
    port: 8080
spring:
    application:
        name: gateway
    cloud:
        config:
            uri: http://localhost:8888						

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

zuul:
    routes:
        astrolab:
            path: /**