server:
  port: 8080
  wait-time-in-ms-when-sync-empty: 3000

spring:
  application:
    name: astrolab-zuul-server
  boot:
    admin:
      client:
        url: ${MONITORING_SERVER_URL:http://localhost:9080}
        

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
      

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
zuul:
  routes:
    astrolab:
      path: /**
      stripPrefix: false