server:
  port: 9091
  wait-time-in-ms-when-sync-empty: 3000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
      

spring:
  boot:
    admin:
      client:
        url: ${MONITORING_SERVER_URL:http://localhost:9080}
        
management:
  endpoints:
    web:
      exposure:
        include: "*"