server:
  port: 9091

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
      
  server:
    wait-time-in-ms-when-sync-empty: 3000
