server:
    port: 9080
spring:
    application:
        name: astrolab-monitoring-server
    cloud:
        config:
            uri: http://localhost:9080          

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
